AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Go-vue-portal-starter admin

Globals:
  Function:
    Timeout: 5

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin
      Handler: app
      Runtime: go1.x
      Tracing: Active
      Events:
        Http:
          Type: Api
          Properties:
            Path: /admin/graphql
            Method: ANY

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  S3FrontendBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref FrontendBucket
        PolicyDocument:
          Statement:
            - Effect: "Allow"
              Principal: '*'
              Action:
                - "s3:GetObject"
              Resource: !Sub "${FrontendBucket.Arn}/*"            